// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: user-service/proto/user_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	PathParamsTest(ctx context.Context, in *PathParamsRequest, opts ...grpc.CallOption) (*PathParamResponse, error)
	PathParamTest(ctx context.Context, in *PathParamRequest, opts ...grpc.CallOption) (*PathParamResponse, error)
	PathParamsAndBodyTest(ctx context.Context, in *PathParamsAndBodyRequest, opts ...grpc.CallOption) (*PathParamResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PathParamsTest(ctx context.Context, in *PathParamsRequest, opts ...grpc.CallOption) (*PathParamResponse, error) {
	out := new(PathParamResponse)
	err := c.cc.Invoke(ctx, "/UserService/PathParamsTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PathParamTest(ctx context.Context, in *PathParamRequest, opts ...grpc.CallOption) (*PathParamResponse, error) {
	out := new(PathParamResponse)
	err := c.cc.Invoke(ctx, "/UserService/PathParamTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PathParamsAndBodyTest(ctx context.Context, in *PathParamsAndBodyRequest, opts ...grpc.CallOption) (*PathParamResponse, error) {
	out := new(PathParamResponse)
	err := c.cc.Invoke(ctx, "/UserService/PathParamsAndBodyTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	PathParamsTest(context.Context, *PathParamsRequest) (*PathParamResponse, error)
	PathParamTest(context.Context, *PathParamRequest) (*PathParamResponse, error)
	PathParamsAndBodyTest(context.Context, *PathParamsAndBodyRequest) (*PathParamResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) PathParamsTest(context.Context, *PathParamsRequest) (*PathParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathParamsTest not implemented")
}
func (UnimplementedUserServiceServer) PathParamTest(context.Context, *PathParamRequest) (*PathParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathParamTest not implemented")
}
func (UnimplementedUserServiceServer) PathParamsAndBodyTest(context.Context, *PathParamsAndBodyRequest) (*PathParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathParamsAndBodyTest not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PathParamsTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PathParamsTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/PathParamsTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PathParamsTest(ctx, req.(*PathParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PathParamTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PathParamTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/PathParamTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PathParamTest(ctx, req.(*PathParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PathParamsAndBodyTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathParamsAndBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PathParamsAndBodyTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/PathParamsAndBodyTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PathParamsAndBodyTest(ctx, req.(*PathParamsAndBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "PathParamsTest",
			Handler:    _UserService_PathParamsTest_Handler,
		},
		{
			MethodName: "PathParamTest",
			Handler:    _UserService_PathParamTest_Handler,
		},
		{
			MethodName: "PathParamsAndBodyTest",
			Handler:    _UserService_PathParamsAndBodyTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service/proto/user_service.proto",
}
