gateway_route: "api/shop"
services:
  user:
    address: user_service:8080
    service_route: /user
    grpc_methods:
      GetUser:
        method_route: /{param}
        type: GET
      DeleteUser:
        method_route: /{param}
        type: DELETE
      CreateUser:
        method_route: /create
        type: POST
  order:
    address: order_service:8080
    service_route: /order

